//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.18 at 10:30:01 AM IST 
//


package com.reactiveworks.jaxbexercise.generatedbean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.reactiveworks.jaxbexercise.generatedbean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.reactiveworks.jaxbexercise.generatedbean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LeapDataServices }
     * 
     */
    public LeapDataServices createLeapDataServices() {
        return new LeapDataServices();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link EntityFields }
     * 
     */
    public EntityFields createEntityFields() {
        return new EntityFields();
    }

    /**
     * Create an instance of {@link EntityCollection }
     * 
     */
    public EntityCollection createEntityCollection() {
        return new EntityCollection();
    }

    /**
     * Create an instance of {@link EntityAccessConfig }
     * 
     */
    public EntityAccessConfig createEntityAccessConfig() {
        return new EntityAccessConfig();
    }

    /**
     * Create an instance of {@link EntityTable }
     * 
     */
    public EntityTable createEntityTable() {
        return new EntityTable();
    }

    /**
     * Create an instance of {@link EntityAccess }
     * 
     */
    public EntityAccess createEntityAccess() {
        return new EntityAccess();
    }

    /**
     * Create an instance of {@link EntityReadKeysMapping }
     * 
     */
    public EntityReadKeysMapping createEntityReadKeysMapping() {
        return new EntityReadKeysMapping();
    }

    /**
     * Create an instance of {@link EntityFilterKeysMapping }
     * 
     */
    public EntityFilterKeysMapping createEntityFilterKeysMapping() {
        return new EntityFilterKeysMapping();
    }

    /**
     * Create an instance of {@link EntityInsertKeysMapping }
     * 
     */
    public EntityInsertKeysMapping createEntityInsertKeysMapping() {
        return new EntityInsertKeysMapping();
    }

    /**
     * Create an instance of {@link EntityUpdateKeysMapping }
     * 
     */
    public EntityUpdateKeysMapping createEntityUpdateKeysMapping() {
        return new EntityUpdateKeysMapping();
    }

    /**
     * Create an instance of {@link LDCResponseConfigs }
     * 
     */
    public LDCResponseConfigs createLDCResponseConfigs() {
        return new LDCResponseConfigs();
    }

    /**
     * Create an instance of {@link ApplyLDCConfig }
     * 
     */
    public ApplyLDCConfig createApplyLDCConfig() {
        return new ApplyLDCConfig();
    }

    /**
     * Create an instance of {@link LDCSchema }
     * 
     */
    public LDCSchema createLDCSchema() {
        return new LDCSchema();
    }

    /**
     * Create an instance of {@link LDCProjection }
     * 
     */
    public LDCProjection createLDCProjection() {
        return new LDCProjection();
    }

    /**
     * Create an instance of {@link LDCTaxonomy }
     * 
     */
    public LDCTaxonomy createLDCTaxonomy() {
        return new LDCTaxonomy();
    }

    /**
     * Create an instance of {@link EntityKey }
     * 
     */
    public EntityKey createEntityKey() {
        return new EntityKey();
    }

    /**
     * Create an instance of {@link EntityColumns }
     * 
     */
    public EntityColumns createEntityColumns() {
        return new EntityColumns();
    }

    /**
     * Create an instance of {@link EntityIndexs }
     * 
     */
    public EntityIndexs createEntityIndexs() {
        return new EntityIndexs();
    }

    /**
     * Create an instance of {@link EntityIndex }
     * 
     */
    public EntityIndex createEntityIndex() {
        return new EntityIndex();
    }

    /**
     * Create an instance of {@link EntityColumn }
     * 
     */
    public EntityColumn createEntityColumn() {
        return new EntityColumn();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link EntityField }
     * 
     */
    public EntityField createEntityField() {
        return new EntityField();
    }

}
