
package com.rxwwebservice.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-11T15:10:53.748+05:30
 * Generated source version: 3.2.12
 */

@WebFault(name = "UserDAOException", targetNamespace = "http://userdao.rxwwebservice.com")
public class UserDAOException_Exception extends Exception {

    private com.rxwwebservice.stubs.UserDAOException userDAOException;

    public UserDAOException_Exception() {
        super();
    }

    public UserDAOException_Exception(String message) {
        super(message);
    }

    public UserDAOException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UserDAOException_Exception(String message, com.rxwwebservice.stubs.UserDAOException userDAOException) {
        super(message);
        this.userDAOException = userDAOException;
    }

    public UserDAOException_Exception(String message, com.rxwwebservice.stubs.UserDAOException userDAOException, java.lang.Throwable cause) {
        super(message, cause);
        this.userDAOException = userDAOException;
    }

    public com.rxwwebservice.stubs.UserDAOException getFaultInfo() {
        return this.userDAOException;
    }
}
