package com.rxwwebservice.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-11T15:10:53.919+05:30
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://userdao.rxwwebservice.com", name = "UserOperation")
@XmlSeeAlso({ObjectFactory.class})
public interface UserOperation {

    @WebMethod
    @RequestWrapper(localName = "createNewUserOperation", targetNamespace = "http://userdao.rxwwebservice.com", className = "com.rxwwebservice.stubs.CreateNewUserOperation")
    @ResponseWrapper(localName = "createNewUserOperationResponse", targetNamespace = "http://userdao.rxwwebservice.com", className = "com.rxwwebservice.stubs.CreateNewUserOperationResponse")
    @WebResult(name = "createUserResult", targetNamespace = "")
    public java.lang.String createNewUserOperation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.rxwwebservice.stubs.User arg0
    ) throws UserDAOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getUserByUserIdOperation", targetNamespace = "http://userdao.rxwwebservice.com", className = "com.rxwwebservice.stubs.GetUserByUserIdOperation")
    @ResponseWrapper(localName = "getUserByUserIdOperationResponse", targetNamespace = "http://userdao.rxwwebservice.com", className = "com.rxwwebservice.stubs.GetUserByUserIdOperationResponse")
    @WebResult(name = "getUserByIdResult", targetNamespace = "")
    public com.rxwwebservice.stubs.User getUserByUserIdOperation(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws UserDAOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteUserByUserIdOperation", targetNamespace = "http://userdao.rxwwebservice.com", className = "com.rxwwebservice.stubs.DeleteUserByUserIdOperation")
    @ResponseWrapper(localName = "deleteUserByUserIdOperationResponse", targetNamespace = "http://userdao.rxwwebservice.com", className = "com.rxwwebservice.stubs.DeleteUserByUserIdOperationResponse")
    @WebResult(name = "deleteUserByIdResult", targetNamespace = "")
    public java.lang.String deleteUserByUserIdOperation(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws UserDAOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getUserByUserNameOperation", targetNamespace = "http://userdao.rxwwebservice.com", className = "com.rxwwebservice.stubs.GetUserByUserNameOperation")
    @ResponseWrapper(localName = "getUserByUserNameOperationResponse", targetNamespace = "http://userdao.rxwwebservice.com", className = "com.rxwwebservice.stubs.GetUserByUserNameOperationResponse")
    @WebResult(name = "getUserByNameResult", targetNamespace = "")
    public com.rxwwebservice.stubs.User getUserByUserNameOperation(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws UserDAOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateExistingUserOperation", targetNamespace = "http://userdao.rxwwebservice.com", className = "com.rxwwebservice.stubs.UpdateExistingUserOperation")
    @ResponseWrapper(localName = "updateExistingUserOperationResponse", targetNamespace = "http://userdao.rxwwebservice.com", className = "com.rxwwebservice.stubs.UpdateExistingUserOperationResponse")
    @WebResult(name = "updateUserResult", targetNamespace = "")
    public java.lang.String updateExistingUserOperation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.rxwwebservice.stubs.User arg0
    ) throws UserDAOException_Exception;
}
