package com.rxwwebservice.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-11T15:10:53.948+05:30
 * Generated source version: 3.2.12
 *
 */
@WebServiceClient(name = "UserOperationService",
                  wsdlLocation = "file:/G:/EclipseIDE/JAVA_RW/usercrudsoap/WebContent/wsdl/useroperationimpl.wsdl",
                  targetNamespace = "http://userdao.rxwwebservice.com")
public class UserOperationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://userdao.rxwwebservice.com", "UserOperationService");
    public final static QName UserOperationImplPort = new QName("http://userdao.rxwwebservice.com", "UserOperationImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/G:/EclipseIDE/JAVA_RW/usercrudsoap/WebContent/wsdl/useroperationimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserOperationService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/G:/EclipseIDE/JAVA_RW/usercrudsoap/WebContent/wsdl/useroperationimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserOperationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserOperationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserOperationService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UserOperationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserOperationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserOperationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UserOperation
     */
    @WebEndpoint(name = "UserOperationImplPort")
    public UserOperation getUserOperationImplPort() {
        return super.getPort(UserOperationImplPort, UserOperation.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserOperation
     */
    @WebEndpoint(name = "UserOperationImplPort")
    public UserOperation getUserOperationImplPort(WebServiceFeature... features) {
        return super.getPort(UserOperationImplPort, UserOperation.class, features);
    }

}
