package com.reactiveworks.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-12T11:48:03.348+05:30
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://product.webservice.rwx.com", name = "ProductOperation")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductOperation {

    @WebMethod
    @RequestWrapper(localName = "createProductOperation", targetNamespace = "http://product.webservice.rwx.com", className = "com.reactiveworks.webservice.CreateProductOperation")
    @ResponseWrapper(localName = "createProductOperationResponse", targetNamespace = "http://product.webservice.rwx.com", className = "com.reactiveworks.webservice.CreateProductOperationResponse")
    @WebResult(name = "create-result", targetNamespace = "")
    public java.lang.String createProductOperation(
        @WebParam(name = "product", targetNamespace = "")
        com.reactiveworks.webservice.Product product
    ) throws ProductDAOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProductByNameOperation", targetNamespace = "http://product.webservice.rwx.com", className = "com.reactiveworks.webservice.GetProductByNameOperation")
    @ResponseWrapper(localName = "getProductByNameOperationResponse", targetNamespace = "http://product.webservice.rwx.com", className = "com.reactiveworks.webservice.GetProductByNameOperationResponse")
    @WebResult(name = "product", targetNamespace = "")
    public com.reactiveworks.webservice.Product getProductByNameOperation(
        @WebParam(name = "product-name", targetNamespace = "")
        java.lang.String productName
    ) throws ProductDAOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateProductOperation", targetNamespace = "http://product.webservice.rwx.com", className = "com.reactiveworks.webservice.UpdateProductOperation")
    @ResponseWrapper(localName = "updateProductOperationResponse", targetNamespace = "http://product.webservice.rwx.com", className = "com.reactiveworks.webservice.UpdateProductOperationResponse")
    @WebResult(name = "udpate-result", targetNamespace = "")
    public java.lang.String updateProductOperation(
        @WebParam(name = "product", targetNamespace = "")
        com.reactiveworks.webservice.Product product
    ) throws ProductDAOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProductByIdOperation", targetNamespace = "http://product.webservice.rwx.com", className = "com.reactiveworks.webservice.GetProductByIdOperation")
    @ResponseWrapper(localName = "getProductByIdOperationResponse", targetNamespace = "http://product.webservice.rwx.com", className = "com.reactiveworks.webservice.GetProductByIdOperationResponse")
    @WebResult(name = "product", targetNamespace = "")
    public com.reactiveworks.webservice.Product getProductByIdOperation(
        @WebParam(name = "product-id", targetNamespace = "")
        java.lang.String productId
    ) throws ProductDAOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteProductOperation", targetNamespace = "http://product.webservice.rwx.com", className = "com.reactiveworks.webservice.DeleteProductOperation")
    @ResponseWrapper(localName = "deleteProductOperationResponse", targetNamespace = "http://product.webservice.rwx.com", className = "com.reactiveworks.webservice.DeleteProductOperationResponse")
    @WebResult(name = "delete-result", targetNamespace = "")
    public java.lang.String deleteProductOperation(
        @WebParam(name = "product-id", targetNamespace = "")
        java.lang.String productId
    ) throws ProductDAOException_Exception;
}
