package com.reactiveworks.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-12T11:48:03.378+05:30
 * Generated source version: 3.2.12
 *
 */
@WebServiceClient(name = "ProductOperationService",
                  wsdlLocation = "file:/G:/EclipseIDE/JAVA_RW/productwithsoap/src/main/webapp/WEB-INF/wsdl/product.wsdl",
                  targetNamespace = "http://product.webservice.rwx.com")
public class ProductOperationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://product.webservice.rwx.com", "ProductOperationService");
    public final static QName ProductOperation = new QName("http://product.webservice.rwx.com", "ProductOperation");
    static {
        URL url = null;
        try {
            url = new URL("file:/G:/EclipseIDE/JAVA_RW/productwithsoap/src/main/webapp/WEB-INF/wsdl/product.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductOperationService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/G:/EclipseIDE/JAVA_RW/productwithsoap/src/main/webapp/WEB-INF/wsdl/product.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductOperationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductOperationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductOperationService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ProductOperationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProductOperationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProductOperationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ProductOperation
     */
    @WebEndpoint(name = "ProductOperation")
    public ProductOperation getProductOperation() {
        return super.getPort(ProductOperation, ProductOperation.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductOperation
     */
    @WebEndpoint(name = "ProductOperation")
    public ProductOperation getProductOperation(WebServiceFeature... features) {
        return super.getPort(ProductOperation, ProductOperation.class, features);
    }

}
