//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.18 at 10:16:41 AM IST 
//


package com.reactiveworks.jaxb.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FeatureImplementations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FeatureImplementation" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="resourceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StaticFileConfiguration">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ConfigFile">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="filePath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DBConfiguration">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="database">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="table" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="column" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="primaryKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                               &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                               &lt;attribute name="autoIncrement" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                               &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="vendorName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vendorVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="implementationName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "featureImplementations",
    "staticFileConfiguration",
    "dbConfiguration"
})
public class Feature {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "FeatureImplementations", required = true)
    protected FeatureImplementations featureImplementations;
    @XmlElement(name = "StaticFileConfiguration", required = true)
    protected StaticFileConfiguration staticFileConfiguration;
    @XmlElement(name = "DBConfiguration", required = true)
    protected DBConfiguration dbConfiguration;
    @XmlAttribute(name = "vendorName", required = true)
    protected String vendorName;
    @XmlAttribute(name = "vendorVersion", required = true)
    protected float vendorVersion;
    @XmlAttribute(name = "implementationName", required = true)
    protected String implementationName;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the featureImplementations property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureImplementations }
     *     
     */
    public FeatureImplementations getFeatureImplementations() {
        return featureImplementations;
    }

    /**
     * Sets the value of the featureImplementations property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureImplementations }
     *     
     */
    public void setFeatureImplementations(FeatureImplementations value) {
        this.featureImplementations = value;
    }

    /**
     * Gets the value of the staticFileConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link StaticFileConfiguration }
     *     
     */
    public StaticFileConfiguration getStaticFileConfiguration() {
        return staticFileConfiguration;
    }

    /**
     * Sets the value of the staticFileConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticFileConfiguration }
     *     
     */
    public void setStaticFileConfiguration(StaticFileConfiguration value) {
        this.staticFileConfiguration = value;
    }

    /**
     * Gets the value of the dbConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link DBConfiguration }
     *     
     */
    public DBConfiguration getDBConfiguration() {
        return dbConfiguration;
    }

    /**
     * Sets the value of the dbConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBConfiguration }
     *     
     */
    public void setDBConfiguration(DBConfiguration value) {
        this.dbConfiguration = value;
    }

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the vendorVersion property.
     * 
     */
    public float getVendorVersion() {
        return vendorVersion;
    }

    /**
     * Sets the value of the vendorVersion property.
     * 
     */
    public void setVendorVersion(float value) {
        this.vendorVersion = value;
    }

    /**
     * Gets the value of the implementationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementationName() {
        return implementationName;
    }

    /**
     * Sets the value of the implementationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementationName(String value) {
        this.implementationName = value;
    }

}
