//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.18 at 10:16:41 AM IST 
//


package com.reactiveworks.jaxb.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.reactiveworks.jaxb.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.reactiveworks.jaxb.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FeatureMetainfo }
     * 
     */
    public FeatureMetainfo createFeatureMetainfo() {
        return new FeatureMetainfo();
    }

    /**
     * Create an instance of {@link FeatureGroup }
     * 
     */
    public FeatureGroup createFeatureGroup() {
        return new FeatureGroup();
    }

    /**
     * Create an instance of {@link Features }
     * 
     */
    public Features createFeatures() {
        return new Features();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeature() {
        return new Feature();
    }

    /**
     * Create an instance of {@link FeatureImplementations }
     * 
     */
    public FeatureImplementations createFeatureImplementations() {
        return new FeatureImplementations();
    }

    /**
     * Create an instance of {@link StaticFileConfiguration }
     * 
     */
    public StaticFileConfiguration createStaticFileConfiguration() {
        return new StaticFileConfiguration();
    }

    /**
     * Create an instance of {@link DBConfiguration }
     * 
     */
    public DBConfiguration createDBConfiguration() {
        return new DBConfiguration();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link ConfigFile }
     * 
     */
    public ConfigFile createConfigFile() {
        return new ConfigFile();
    }

    /**
     * Create an instance of {@link FeatureImplementation }
     * 
     */
    public FeatureImplementation createFeatureImplementation() {
        return new FeatureImplementation();
    }

}
